use mavenmovies;
describe actor;
select * from actor;
select * from customer;
select * from country;
select distinct country from country;
select * from customer where active = 1;
select * from rental;
select rental_id, customer_id from rental where customer_id=1;
select title, rental_duration from film where rental_duration>5;
select * from customer;
select count(title) from film where replacement_cost >15 and replacement_cost<20;
select count( distinct first_name) from actor;
select * from customer limit 10;
select * from customer where first_name like 'b%';
select * from film where rating = 'G' LIMIT 5;
select first_name from customer WHERE first_name LIKE '%NI%';
select first_name from customer WHERE first_name LIKE 'a%' and length(first_name) >= 5;
select first_name from customer WHERE first_name LIKE 'a%o';
select * from film where length between 50 and 100;
select * from actor limit 50;
select distinct film_id from inventory;